services:
  - type: web
    name: youtube-audio-api
    env: python
    region: india
    plan: free
    buildCommand: |
      apt-get update -y
      apt-get install -y ffmpeg
      apt-get install -y ffmpeg-doc
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app --timeout 200
